"""Compare top-k logprobs from vLLM and llama-server at multiple decode positions.

Drives the conversation forward in lockstep: at each step, take the assistant
text generated by vLLM up to position N, feed it as a fixed prefix to both
servers via the chat history, and ask each for top_logprobs at the next token.
Quantifies how much the two distributions diverge as the decode position
grows.
"""
import json
import os
from datetime import datetime, timedelta
from pathlib import Path

from huggingface_hub import hf_hub_download
from openai import OpenAI


def load_system_prompt() -> str:
    p = hf_hub_download(repo_id="mistralai/Mistral-Medium-3.5-128B", filename="SYSTEM_PROMPT.txt")
    raw = Path(p).read_text()
    today = datetime.today().strftime("%Y-%m-%d")
    yesterday = (datetime.today() - timedelta(days=1)).strftime("%Y-%m-%d")
    return raw.format(name="Mistral-Medium-3.5-128B", today=today, yesterday=yesterday)


SYSTEM_PROMPT = load_system_prompt()
USER_PROMPT = "Create a Flappy Bird Python game"


def topk_at_prefix(base_url: str, prefix_text: str, top_k: int = 20) -> list:
    """Get top-k logprobs for the next token after assistant has produced prefix_text."""
    client = OpenAI(api_key="EMPTY", base_url=base_url)
    model = client.models.list().data[0].id
    msgs = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": USER_PROMPT},
    ]
    # Trick: use assistant turn with `partial_assistant_message`/prefix isn't standard.
    # Instead, render a continuation completion via /v1/completions on the raw text.
    # vLLM accepts /v1/completions; llama-server too.
    return None  # placeholder


# Different approach: do a vLLM-only full greedy decode of 1500 tokens, then for
# each checkpoint position, query both servers' top_logprobs at that token.

def main():
    OUT = Path("outputs/diag_logits_progression.json")
    OUT.parent.mkdir(parents=True, exist_ok=True)

    # Step 1: get vLLM's full greedy decode.
    vllm_client = OpenAI(api_key="EMPTY", base_url="http://localhost:8765/v1")
    vllm_model = vllm_client.models.list().data[0].id
    print(f"vLLM model: {vllm_model}")

    base_msgs = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": USER_PROMPT},
    ]
    r = vllm_client.chat.completions.create(
        model=vllm_model,
        messages=base_msgs,
        temperature=0.0,
        max_tokens=1500,
        logprobs=True,
        top_logprobs=20,
        extra_body={"reasoning_effort": "none", "return_tokens_as_token_ids": True},
    )
    vllm_full_text = r.choices[0].message.content or ""
    print(f"vLLM total tokens: {r.usage.completion_tokens}")
    print(f"vLLM finish: {r.choices[0].finish_reason}")
    print(f"vLLM head: {vllm_full_text[:80]!r}")

    # Step 2: at checkpoints (token 50, 200, 500, 1000, 1400), reconstruct the
    # same prefix and query llama-server's top-20.
    checkpoints = [50, 200, 500, 1000, 1400]
    samples = []

    # We need to send a partial assistant turn. The OpenAI chat API doesn't directly
    # support that. Workaround: use /v1/completions with the raw rendered prompt,
    # which BOTH servers expose, by calling render endpoints to assemble.
    import requests

    # Re-fetch vLLM's logprobs.content list — these are token-level entries.
    if r.choices[0].logprobs is None:
        print("no logprobs from vllm")
        return
    vllm_token_entries = r.choices[0].logprobs.content
    # Each entry has .token (formatted as "token_id:NN" since we asked) and .logprob and .top_logprobs

    # Get the rendered prompt as text (chat template applied)
    base_render = requests.post(
        "http://localhost:8766/apply-template",
        json={"messages": base_msgs},
        timeout=60,
    ).json()["prompt"]
    # This is the raw text that, after BOS, becomes the input

    # Get a list of token IDs and decoded text per cumulative output position.
    # We accumulate detokenized characters position by position.
    cumulative_text_at = {}
    cur_ids = []
    for i, tok in enumerate(vllm_token_entries):
        # tok.token looks like "token_id:1035"
        if not tok.token.startswith("token_id:"):
            continue
        try:
            tid = int(tok.token.split(":", 1)[1])
        except Exception:
            continue
        cur_ids.append(tid)
        if (i + 1) in checkpoints:
            # Detokenize up to this point via llama-server (since vLLM detokenize is at /detokenize too)
            txt = requests.post(
                "http://localhost:8766/detokenize",
                json={"tokens": cur_ids},
                timeout=60,
            ).json()["content"]
            cumulative_text_at[i + 1] = txt

    print(f"Captured {len(cumulative_text_at)} checkpoints: {list(cumulative_text_at)}")

    for n_decoded, prefix_text in cumulative_text_at.items():
        # Construct a /v1/completions prompt that mimics the chat completion's KV state.
        # The chat-template-rendered text + the assistant-side prefix.
        # For Mistral chat template, after [INST] xxx [/INST], the assistant emits text
        # without a leading "[ASST]" tag, so we just concatenate.
        full_prompt = base_render + prefix_text

        # Query both servers for next-token top-20 logprobs via /v1/completions.
        sample = {"n_decoded": n_decoded, "prefix_chars": len(prefix_text)}
        for label, base in [("vllm", "http://localhost:8765/v1"), ("llama", "http://localhost:8766/v1")]:
            try:
                rr = requests.post(
                    base + "/completions",
                    json={
                        "model": "mistralai/Mistral-Medium-3.5-128B" if label == "vllm" else "mistralai_Mistral-Medium-3.5-128B-Q8_0-00001-of-00004.gguf",
                        "prompt": full_prompt,
                        "max_tokens": 1,
                        "temperature": 0.0,
                        "logprobs": 20,
                    },
                    timeout=120,
                ).json()
                # parse
                if "choices" in rr and rr["choices"]:
                    ch = rr["choices"][0]
                    lp = ch.get("logprobs") or {}
                    top = lp.get("top_logprobs") or []
                    if isinstance(top, list) and top:
                        # top is a list of dicts {token_str: logprob}
                        sample[label + "_top20"] = top[0]
                        sample[label + "_first_token"] = (lp.get("tokens") or [None])[0]
                    else:
                        sample[label + "_raw"] = rr
            except Exception as e:
                sample[label + "_error"] = str(e)
        samples.append(sample)
        print(f"checkpoint {n_decoded}: {sample.get('vllm_first_token')!r} vs {sample.get('llama_first_token')!r}")

    OUT.write_text(json.dumps({"vllm_full_text": vllm_full_text, "checkpoints": samples}, indent=2))
    print(f"saved {OUT}")


if __name__ == "__main__":
    main()
