"""Emit the ggml C tables for IQ1_XS / IQ1_XXS / IQ1_XXXS.

The three narrow types reuse ggml's own 8-dimensional ternary codebook. Each new grid is a
SUBSET of `iq1s_grid`, selected by imatrix-weighted greedy facility-location on real Kimi-K3
expert weights (`scripts/iq1_narrow_grids/k3_greedy{1024,512,256}.npy`, stored as indices into
the 2048-entry table and verified here to be subsets).

Reusing ggml's entries rather than training fresh ones is deliberate:

  * every entry is already known to be int8-representable, which `ggml_vec_dot_iq1_s_q8_K`
    requires because it reaches the grid through `_mm256_maddubs_epi16`, an int8 dot product;
  * the measured quality of these exact codebooks is already on record, so the C types
    reproduce numbers we have rather than new ones;
  * codebook selection was measured to be a weak lever anyway: three selection criteria agree
    to within 0.5% and selecting from all 6561 ternary patterns instead of ggml's 2048 moves
    weighted nrmse by 0.19%.

Both the CPU (`uint64_t`, 8 packed int8) and CUDA (`uint32_t`, 8 packed 4-bit) mirrors are
emitted, matching the `iq1s_grid` / `iq1s_grid_gpu` pair at ggml-common.h:1135 and :1650.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

import numpy as np

REPO  = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GRIDS = os.path.join(REPO, "scripts", "iq1_narrow_grids")

# name -> (npy of indices into iq1s_grid, entries, index bits, block bytes, bpw)
TYPES = {
    "IQ1_XS":   ("k3_greedy1024.npy", 1024, 10, 46, 1.4375),
    "IQ1_XXS":  ("k3_greedy512.npy",   512,  9, 42, 1.3125),
    "IQ1_XXXS": ("k3_greedy256.npy",   256,  8, 38, 1.1875),
}


def read_ggml_table(path: str, name: str, ctype: str) -> list[int]:
    """Parse GGML_TABLE_BEGIN(ctype, name, N) ... GGML_TABLE_END() out of ggml-common.h."""
    src = open(path).read()
    m = re.search(r"GGML_TABLE_BEGIN\(\s*%s\s*,\s*%s\s*,\s*[A-Z0-9_]+\s*\)(.*?)GGML_TABLE_END\(\)"
                  % (re.escape(ctype), re.escape(name)), src, re.S)
    if not m:
        raise SystemExit(f"{name} ({ctype}) not found in {path}")
    body = m.group(1)
    vals = [int(t, 16) for t in re.findall(r"0x([0-9a-fA-F]+)", body)]
    return vals


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--common", default=os.path.join(REPO, "ggml", "src", "ggml-common.h"))
    ap.add_argument("--out", required=True, help="C fragment to write")
    a = ap.parse_args()

    cpu = read_ggml_table(a.common, "iq1s_grid", "uint64_t")
    gpu = read_ggml_table(a.common, "iq1s_grid_gpu", "uint32_t")
    if len(cpu) != 2048 or len(gpu) != 2048:
        raise SystemExit(f"expected 2048 entries, got cpu={len(cpu)} gpu={len(gpu)}")
    print(f"read iq1s_grid: {len(cpu)} uint64, iq1s_grid_gpu: {len(gpu)} uint32")

    out = ["// Generated by scripts/iqxs_gen_tables.py. Do not edit by hand.",
           "// Subsets of iq1s_grid chosen by imatrix-weighted greedy facility-location on real",
           "// Kimi-K3 expert weights; every entry is an existing ggml grid point, so the int8",
           "// representability ggml_vec_dot_iq1_s_q8_K relies on is inherited rather than assumed.",
           ""]
    for tname, (npy, n, bits, blk, bpw) in TYPES.items():
        idx = np.load(os.path.join(GRIDS, npy))
        if len(idx) != n:
            raise SystemExit(f"{npy}: expected {n} entries, got {len(idx)}")
        if idx.min() < 0 or idx.max() > 2047:
            raise SystemExit(f"{npy}: index out of range [{idx.min()},{idx.max()}]")
        if len(set(idx.tolist())) != n:
            raise SystemExit(f"{npy}: duplicate indices")
        low = tname.lower()
        macro = "NGRID_" + tname.replace("IQ1_", "IQ1")
        out.append(f"#define {macro} {n}")
        for arr, ct, suffix, per in ((cpu, "uint64_t", "", 4), (gpu, "uint32_t", "_gpu", 8)):
            out.append(f"GGML_TABLE_BEGIN({ct}, {low}_grid{suffix}, {macro})")
            vals = [arr[int(i)] for i in idx]
            w = 16 if ct == "uint64_t" else 8
            for i in range(0, n, per):
                row = ", ".join(f"0x{v:0{w}x}" for v in vals[i:i + per])
                out.append("    " + row + ",")
            out.append("GGML_TABLE_END()")
            out.append("")
        print(f"{tname:9s} {n:5d} entries  {bits} bit index  {blk} B/block  {bpw} bpw")

    os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
    open(a.out, "w").write("\n".join(out) + "\n")
    print(f"wrote {a.out} ({len(out)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
